# Generated by Django 3.2.5 on 2021-09-06 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='date_liked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
